version: 1
services:
  - name: web
    type: web
    buildCommand: npm install && npm run build # Lệnh để cài đặt dependencies và xây dựng ứng dụng
    startCommand: npm start # Lệnh để khởi chạy ứng dụng

