version: 1
services:
  - name: web
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
    ports:
      - port: 8080
